changelog:
    exclude:
        labels:
            - release-ignore
        authors:
            - pre-commit-ci
            - pre-commit-ci[bot]
    categories:
        - title: Added
          labels:
              - "release-added"
        - title: Changed
          labels:
              - "release-changed"
        - title: Deprecated
          labels:
              - "release-deprecated"
        - title: Removed
          labels:
              - "release-removed"
        - title: Fixed
          labels:
              - "release-fixed"
        - title: Security
          labels:
              - "release-security"
        - title: Other Changes
          labels:
              - "*"
