# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
    os: ubuntu-20.04
    tools:
        python: "3.10"
    jobs:
        post_install:
            - pip install uv
            - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --extra docs --extra torch --link-mode=copy
sphinx:
    configuration: docs/conf.py
    fail_on_warning: true
submodules:
    include:
        - "docs/tutorials/notebooks"
    recursive: true
