# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
    os: ubuntu-20.04
    tools:
        python: "3.11"
sphinx:
    configuration: docs/conf.py
    fail_on_warning: true
python:
    install:
        - method: pip
          path: .
          extra_requirements:
              - docs
              - torch
submodules:
    include:
        - "docs/tutorials/notebooks"
    recursive: true
