# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
    os: ubuntu-24.04
    tools:
        python: "3.13"
    jobs:
        post_checkout:
            # unshallow so version can be derived from tag
            - git fetch --unshallow || true
        create_environment:
            - asdf plugin add uv
            - asdf install uv latest
            - asdf global uv latest
        build:
            html:
                - uv sync --group=docs --extra=torch
                - uv run make --directory=docs html
                - mv docs/_build $READTHEDOCS_OUTPUT
submodules:
    include:
        - "docs/tutorials/notebooks"
    recursive: true
