"""Extension to inject the current git ref into ``html_context["github_version"]``.

Without this, ``html_context["github_version"]`` is hardcoded and the source links
generated by :mod:`scanpydoc.rtd_github_links` always point at ``main``, so line
numbers on released docs drift away from the code the page documents.

Adapted from scanpy's ``docs/extensions/git_ref.py``, which injects the ref into
``html_theme_options["repository_branch"]`` instead; ``scanpydoc.rtd_github_links``
prefers ``html_context`` over ``html_theme_options``, and this project defines the
former, so we set it there.
"""

from __future__ import annotations

import os
import re
import subprocess
from functools import lru_cache
from typing import TYPE_CHECKING

from sphinx.util.typing import ExtensionMetadata

if TYPE_CHECKING:
    from sphinx.application import Sphinx
    from sphinx.config import Config


def git(*args: str) -> str:
    """Run a git command and return the output as a string."""
    return subprocess.check_output(["git", *args]).strip().decode()


# https://github.com/DisnakeDev/disnake/blob/7853da70b13fcd2978c39c0b7efa59b34d298186/docs/conf.py#L192
@lru_cache
def get() -> str | None:
    """Get current git reference.

    Uses branch/tag name if found, otherwise uses commit hash.
    """
    # On Read the Docs pull request previews, HEAD is a local branch such as
    # "external-1185" that does not exist on GitHub, so use the commit instead.
    # GitHub serves a pull request's head commit from the base repository, also
    # when the branch itself lives on a fork.
    if os.environ.get("READTHEDOCS_VERSION_TYPE") == "external" and (
        commit := os.environ.get("READTHEDOCS_GIT_COMMIT_HASH")
    ):
        return commit

    git_ref = None
    try:
        git_ref = git("name-rev", "--name-only", "--no-undefined", "HEAD")
        git_ref = re.sub(r"^(remotes/[^/]+|tags)/", "", git_ref)
    except Exception:  # noqa: BLE001
        pass

    # (if no name found or relative ref, use commit hash instead)
    if not git_ref or re.search(r"[\^~]", git_ref):
        try:
            git_ref = git("rev-parse", "HEAD")
        except Exception:  # noqa: BLE001
            git_ref = "main"
    return git_ref


def set_ref(app: Sphinx, config: Config):
    """`config-inited` hook to set `html_context["github_version"]`."""
    app.config["html_context"]["github_version"] = get() or "main"


def setup(app: Sphinx) -> ExtensionMetadata:
    """App setup hook."""
    app.connect("config-inited", set_ref)
    return ExtensionMetadata(parallel_read_safe=True)
