from __future__ import annotations

from spatialdata.transformations._graph.edge import (
    AffineEdge,
    BaseTransformationEdge,
    ByDimensionEdge,
    CsGen,
    IdentityEdge,
    MapAxisEdge,
    ProjectAxisEdge,
    RotationEdge,
    ScaleEdge,
    SequenceEdge,
    TranslationEdge,
    parse_affine,
    parse_by_dimension,
    parse_identity,
    parse_map_axis,
    parse_ngff_transf,
    parse_project_axis,
    parse_rotation,
    parse_scale,
    parse_sequence,
    parse_translation,
)
from spatialdata.transformations._graph.exceptions import (
    AxisRedefinitionError,
    CannotRemoveCoordinateSystemError,
    CoordinateSystemAlreadyExistsError,
    CoordinateSystemNotFoundError,
    DeterminantDifferentFromOne,
    ElementAlreadyExistsError,
    ElementNotRegisteredToAnyCoordinateSystemError,
    EmptyTransformSequenceError,
    IncompatibleCoordSystemsError,
    InvalidPathError,
    MissingAxisError,
    NGFFCompatibilityError,
    NotOrthonormalError,
    TransformationNotFoundError,
    TransformationPathAmbiguousError,
    TransformationPathAmbiguousMultipleEdgeExpectedError,
    TransformationPathAmbiguousNoEdgeExpectedError,
    TransformationPathNotFoundError,
    TransformationPathNotSimple,
    UnexpectedShapeError,
    UnmappedAxisError,
)
from spatialdata.transformations._graph.graph import TransformationGraph
from spatialdata.transformations._graph.literals import TRANSFORM_KEY
from spatialdata.transformations._graph.utils import get_default_coordinate_system
from spatialdata.transformations._graph.vert import Axis, CoordSystem

__all__ = [
    # from edge
    "AffineEdge",
    "BaseTransformationEdge",
    "ByDimensionEdge",
    "CsGen",
    "IdentityEdge",
    "MapAxisEdge",
    "ProjectAxisEdge",
    "RotationEdge",
    "ScaleEdge",
    "SequenceEdge",
    "TranslationEdge",
    "parse_affine",
    "parse_by_dimension",
    "parse_identity",
    "parse_map_axis",
    "parse_ngff_transf",
    "parse_project_axis",
    "parse_rotation",
    "parse_scale",
    "parse_sequence",
    "parse_translation",
    # from exceptions
    "AxisRedefinitionError",
    "CannotRemoveCoordinateSystemError",
    "CoordinateSystemAlreadyExistsError",
    "CoordinateSystemNotFoundError",
    "DeterminantDifferentFromOne",
    "ElementAlreadyExistsError",
    "ElementNotRegisteredToAnyCoordinateSystemError",
    "EmptyTransformSequenceError",
    "IncompatibleCoordSystemsError",
    "InvalidPathError",
    "MissingAxisError",
    "NGFFCompatibilityError",
    "NotOrthonormalError",
    "TransformationNotFoundError",
    "TransformationPathAmbiguousError",
    "TransformationPathAmbiguousMultipleEdgeExpectedError",
    "TransformationPathAmbiguousNoEdgeExpectedError",
    "TransformationPathNotFoundError",
    "TransformationPathNotSimple",
    "UnexpectedShapeError",
    "UnmappedAxisError",
    # from graph
    "TransformationGraph",
    # from literals
    "TRANSFORM_KEY",
    # from utils
    "get_default_coordinate_system",
    # from vert
    "Axis",
    "CoordSystem",
]
