name: build image
# adapted from https://github.com/scverse/scvi-tools/blob/main/.github/workflows/build_image_latest.yaml

on:
    workflow_run:
        workflows: ["Release"]
        types:
            - completed
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/v') }}
        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash -e {0} # -e to fail on error

        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - uses: docker/setup-buildx-action@v3

            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set build inputs
              id: build
              run: |
                  INPUT_REF=${{ github.ref_name }}
                  if [[ $INPUT_REF == "main" ]]; then
                    VERSION="latest"
                  else
                    VERSION=${INPUT_REF}
                  fi
                  echo "version=${VERSION}" >> $GITHUB_OUTPUT

            - uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  cache-from: type=registry,ref=ghcr.io/scverse/spatialdata:buildcache
                  cache-to: type=inline,ref=ghcr.io/scverse/spatialdata:buildcache
                  target: build
                  tags: ghcr.io/scverse/spatialdata:${{ steps.build.outputs.version }}
